completed api-authentication
BrianBozi/rc0521-code-solutions pull request #121
Opened 2021-07-16 17:04 UTC by BrianBozi

![Screen Shot 2021-07-16 at 10 04 17 AM](https://user-images.githubusercontent.com/70422100/125983706-22693ff9-5d08-40d0-8323-abe24a2e3b0b.png)

2021-07-16 17:39 UTC, Zhiwutian requested changes
Great work, small update!

2021-07-16 17:39 UTC, Zhiwutian commented on api-authentication/server/index.js
> +    .then(isMacthing => {
Hey Brian, the only update here is that if it does not match you want to send back a 401 client error.

2021-07-19 06:01 UTC, BrianBozi commented
![Screen Shot 2021-07-18 at 11 01 33 PM](https://user-images.githubusercontent.com/70422100/126110315-cb3434d2-ba5c-4b02-8a42-d74df3050d03.png)

2021-07-19 18:25 UTC, scbowler approved these changes
Looks good! 👍 

1 FYI comment, no changes required

2021-07-19 18:25 UTC, scbowler commented on api-authentication/server/index.js
> +      console.log("does the password match?",isMatching)
Remember to remove any console logs before submitting a PR

2021-07-19 19:50 UTC, merged