completed javascript-if
BrianBozi/rc0521-code-solutions pull request #32
Opened 2021-05-12 19:00 UTC by BrianBozi

![image](https://user-images.githubusercontent.com/70422100/118030080-b0669800-b319-11eb-9fc8-2a2a078f45da.png)

2021-05-12 21:35 UTC, scbowler requested changes
A couple small changes needed

2021-05-12 21:35 UTC, scbowler commented on javascript-if/main.js
> +  if (number < 21) {
Should be checking if under 5 not 21

2021-05-12 21:35 UTC, scbowler commented on javascript-if/main.js
> +  }
If `ph` is `-20` this will return `acid` when it should return `invalid ph level`. Needs a little reworking on the logic.

2021-05-13 16:47 UTC, BrianBozi commented
![image](https://user-images.githubusercontent.com/70422100/118158055-27f6fe80-b3d0-11eb-9201-790c1f687a36.png)

2021-05-13 16:55 UTC, Zhiwutian approved these changes
👍🏼

2021-05-15 00:51 UTC, merged